image: gradle

stages:
  - build
  - release

test:
  stage: build
  script:
    - gradle test --no-daemon
  tags:
    - docker
pages:
  stage: build
  script:
    - gradle dokka --no-daemon
  artifacts:
    paths:
      - docs
  tags:
    - docker
  only:
    - master
releaseToBintray:
  stage: release
  script:
    - gradle bintrayUpload --no-daemon
  artifacts:
    paths:
      - build/libs
  tags:
    - docker
  only:
    - master
