image: gradle

stages:
  - build
  - release

test:
  stage: build
  script:
    - gradle test
  artifacts:
    paths:
      - build/libs/
  tags:
    - docker
document:
  stage: build
  script:
    - gradle dokka
  artifacts:
    paths:
      - docs/
  tags:
    - docker
releaseToBintray:
  stage: release
  script:
    - gradle bintrayUpload
  tags:
    - docker
  only:
    - master
