image: gradle

stages:
  - build
  - release

test:
  stage: build
  script:
    - gradle test --no-daemon
  tags:
    - docker

pages:
  stage: build
  script:
    - gradle dokka --no-daemon
  artifacts:
    paths:
      - public/
  tags:
    - docker
  only:
    - master

publishSnapshot:
  stage: release
  script:
    - gradle publishJvmPublicationToGitlabRepository --no-daemon
  tags:
    - docker
  only:
    - develop

publishReleaseVersion:
  stage: release
  script:
    - gradle bintrayUpload publishJvmPublicationToGitlabRepository --no-daemon
  tags:
    - docker
  only:
    - master
  when: manual
