image: gradle:7.6

variables:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

stages:
  - build
  - release

test:
  stage: build
  script:
    - gradle check

pages:
  stage: build
  script:
    - gradle dokkaHtmlMultiModule
  artifacts:
    paths:
      - public/
  only:
    - master

publishDevelopmentVersion:
  stage: release
  script:
    - gradle publishAllPublicationsToOssrhSnapshotsRepository
  tags:
    - docker
  only:
    - develop

publishMavenCentralVersion:
  stage: release
  script:
    - gradle publishAllPublicationsToOssrhStagingRepository
  only:
    - master
  when: manual
