image: gradle

variables:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

stages:
  - build
  - release

test:
  stage: build
  script:
    - gradle check
  tags:
    - docker

pages:
  stage: build
  script:
    - gradle dokka
  artifacts:
    paths:
      - public/
  tags:
    - docker
  only:
    - master

publishSnapshot:
  stage: release
  script:
    - gradle publishJvmPublicationToGitlabRepository
  tags:
    - docker
  only:
    - develop

publishReleaseVersion:
  stage: release
  script:
    - gradle publishJvmPublicationToGitlabRepository bintrayUpload
  tags:
    - docker
  only:
    - master
  when: manual
