image: gradle:5.4.1-alpine

variables:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

stages:
  - build
  - release

test:
  stage: build
  script:
    - gradle check
  tags:
    - docker

pages:
  stage: build
  script:
    - gradle dokka
  artifacts:
    paths:
      - public/
  tags:
    - docker
  only:
    - master

publishDevelopmentVersion:
  stage: release
  script:
    - gradle publishJvmPublicationToGitlabRepository
    - gradle publishMultiplatformPublicationToGitlabRepository
    - gradle publishMetadataPublicationToGitlabRepository
  tags:
    - docker
  only:
    - develop
    - master

publishReleaseVersion:
  stage: release
  script:
    - gradle bintrayUpload
  tags:
    - docker
  only:
    - master
  when: manual
